--- nes_snes_db9_usb-1.9_adapted/Makefile	2013-09-23 23:45:37.000000000 +0400
+++ nes_snes_db9_usb-1.9/Makefile	2011-11-17 08:02:28.000000000 +0400
@@ -8,11 +8,11 @@
 # This Revision: $Id: Makefile,v 1.7 2008-09-13 18:34:09 raph Exp $
 
 UISP = uisp -dprog=stk500 -dpart=atmega8 -dserial=/dev/ttyS1
-COMPILE = avr-gcc -Wall -Os -fdata-sections -ffunction-sections -funsigned-bitfields -fpack-struct  -fshort-enums -funsigned-char -mcall-prologues -Iusbdrv -I. -mmcu=atmega8 -DF_CPU=12000000L #-DDEBUG_LEVEL=1
+COMPILE = avr-gcc -Wall -Os -Iusbdrv -I. -mmcu=atmega8 -DF_CPU=12000000L #-DDEBUG_LEVEL=1
 COMMON_OBJS = usbdrv/usbdrv.o usbdrv/usbdrvasm.o usbdrv/oddebug.o main.o
 HEXFILE=main.hex
 
-OBJS = $(COMMON_OBJS) snes.o nes.o db9.o devdesc.o tg16.o segamtap.o #snesmouse.o
+OBJS = $(COMMON_OBJS) snes.o snesmouse.o nes.o db9.o devdesc.o tg16.o segamtap.o
 
 
 # symbolic targets:
@@ -37,7 +37,7 @@
 
 # file targets:
 main.bin:	$(OBJS)	snes.o nes.o snesmouse.o db9.o tg16.o devdesc.o 
-	$(COMPILE) -o main.bin $(OBJS) -Wl,-Map=main.map -gc-sections,--relax
+	$(COMPILE) -o main.bin $(OBJS) -Wl,-Map=main.map
 
 $(HEXFILE):	main.bin
 	rm -f $(HEXFILE) main.eep.hex
